# Generated by Django 3.2.11 on 2022-02-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0015_auto_20220209_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
