# Generated by Django 3.2.11 on 2022-02-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0020_auto_20220210_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('Phone', 'Phone'), ('Electronics', 'Electronics')], max_length=50, null=True),
        ),
    ]
