# Generated by Django 3.2.11 on 2022-02-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0022_alter_stock_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
