# Generated by Django 3.2.11 on 2022-02-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0024_alter_stock_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_csv',
        ),
    ]
