# Generated by Django 3.2.11 on 2022-02-11 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0029_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 19, 31, 52, 38301, tzinfo=utc)),
        ),
    ]
