# Generated by Django 3.2.11 on 2022-02-12 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0033_auto_20220212_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 22, 1, 57, 317717)),
        ),
        migrations.AlterField(
            model_name='stocklisthistory',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocklisthistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 22, 1, 57, 318720), null=True),
        ),
    ]
