# Generated by Django 3.2.11 on 2022-02-12 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0038_auto_20220212_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 22, 16, 55, 651431)),
        ),
        migrations.AlterField(
            model_name='stocklisthistory',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocklisthistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 22, 16, 55, 652614), null=True),
        ),
    ]
