# Generated by Django 3.2.11 on 2022-02-13 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0039_auto_20220212_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 9, 36, 9, 951662)),
        ),
        migrations.AlterField(
            model_name='stocklisthistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 9, 36, 9, 958259), null=True),
        ),
    ]
