# Generated by Django 3.2.11 on 2022-02-13 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0041_auto_20220213_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklisthistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stocklisthistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stocklisthistory',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='stocklisthistory',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='stocklisthistory',
            name='timestampp',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 9, 48, 59, 971344)),
        ),
        migrations.AlterField(
            model_name='stocklisthistory',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
