# Generated by Django 3.2.11 on 2022-02-13 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0042_auto_20220213_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklisthistory',
            name='issue_by',
        ),
        migrations.RemoveField(
            model_name='stocklisthistory',
            name='issue_to',
        ),
        migrations.RemoveField(
            model_name='stocklisthistory',
            name='receive_by',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 9, 59, 25, 67572)),
        ),
        migrations.AlterField(
            model_name='stocklisthistory',
            name='receive_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
