# Generated by Django 3.2.11 on 2022-02-13 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0043_auto_20220213_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklisthistory',
            name='issue_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocklisthistory',
            name='issue_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocklisthistory',
            name='receive_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 10, 2, 37, 831594)),
        ),
    ]
