# Generated by Django 3.2.11 on 2022-02-13 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0044_auto_20220213_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 10, 3, 49, 473555)),
        ),
        migrations.AlterField(
            model_name='stocklisthistory',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='stock_app.categorie'),
        ),
    ]
