# Generated by Django 3.2.11 on 2022-02-13 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0045_auto_20220213_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklisthistory',
            name='issue_to',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 10, 8, 44, 314482)),
        ),
    ]
