# Generated by Django 3.2.11 on 2022-02-13 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0047_auto_20220213_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 16, 47, 53, 306985)),
        ),
    ]
