# Generated by Django 3.2.11 on 2022-02-13 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0048_auto_20220213_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 17, 5, 34, 135401)),
        ),
    ]
