# Generated by Django 3.2.11 on 2022-02-14 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0050_auto_20220214_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='upload_file',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 21, 25, 54, 734766)),
        ),
    ]
