# Generated by Django 3.2.11 on 2022-02-14 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0051_auto_20220214_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='upload_file',
            field=models.ImageField(blank=True, null=True, upload_to='chapter/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='upload_img',
            field=models.FileField(blank=True, null=True, upload_to='chapter/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 21, 51, 10, 17353)),
        ),
    ]
