# Generated by Django 3.2.11 on 2022-02-14 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0053_auto_20220214_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 21, 54, 22, 456127)),
        ),
    ]
