# Generated by Django 3.2.11 on 2022-02-14 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0055_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='upload_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 21, 57, 29, 175264)),
        ),
    ]
